const text = {
    text0 : "In literary theory, a text is any object that can be 'read', whether this object is a work of literature, a street sign, an arrangement of buildings on a city block, or styles of clothing. It is a coherent set of signs that transmits some kind of informative message.[1] This set of signs is considered in terms of the informative message's content, rather than in terms of its physical form or the medium in which it is represented",

    text1: "In literary theory, a text is any object that can be 'read', whether this object is a work of literature, a street sign, an arrangement of buildings on a city block, or styles of clothing. It is a coherent set of signs that transmits some kind of informative message.[1] This set of signs is considered in terms of the informative message's content, rather than in terms of its physical form or the medium in which it is represented.",

    text2: "Civilization describes a complex way of life that came about as people began to develop networks of urban settlements. The earliest civilizations developed between 4000 and 3000 B.C.E., when the rise of agriculture and trade allowed people to have surplus food and economic stability. Many people no longer had to practice farming, allowing a diverse array of professions and interests to flourish in a relatively confined area. Civilizations first appeared in Mesopotamia (what is now Iraq) and later in Egypt. Civilizations thrived in the Indus Valley by about 2500 B.C.E., in China by about 1500 B.C.E. and in Central America (what is now Mexico) by about 1200 B.C.E. Civilizations ultimately developed on every continent except Antarctica.",

    text3: "All civilizations work to preserve their legacy by building large monuments and structures. This is as true today as it was thousands of years ago. For example, the ancient monuments at Great Zimbabwe are still consistently used as a symbol of political power in the modern nation of Zimbabwe. Great Zimbabwe, constructed between 1100 and 1450, describes the ruins of the capital of the Kingdom of Zimbabwe. At its peak, Great Zimbabwe was inhabited by more than 10,000 people and was part of a trading network that extended from the Maghreb, through the eastern coast of Africa, and as far east as India and China.",

    text4: "In biology, evolution is the change in heritable characteristics of biological populations over successive generations.[1][2] Evolution occurs when evolutionary processes such as natural selection (including sexual selection) and genetic drift act on genetic variation, resulting in certain characteristics becoming more or less common within a population over successive generations.[3] The process of evolution has given rise to biodiversity at every level of biological organisation.",

    text5: "Evolutionary biologists have continued to study various aspects of evolution by forming and testing hypotheses as well as constructing theories based on evidence from the field or laboratory and on data generated by the methods of mathematical and theoretical biology. Their discoveries have influenced not just the development of biology but also other fields including agriculture, medicine, and computer science.",

    text6: "Computer programming is the process of performing particular computations, usually by designing and building executable computer programs. Programming involves tasks such as analysis, generating algorithms, profiling algorithms' accuracy and resource consumption, and the implementation of algorithms.",

    text7: "The programming behind a mobile app can make it possible for you to order food, book a rideshare service, track your fitness, access media, and more with ease.",

    text8: "A blockchain allows the data in a database to be spread out among several network nodes—computers or devices running software for the blockchain—at various locations. This not only creates redundancy but maintains the fidelity of the data. For example, if someone tries to alter a record at one instance of the database, the other nodes would prevent it from happening. This way, no single node within the network can alter information held within it. Because of this distribution—and the encrypted proof that work was done—the information and history like the transactions in cryptocurrency are irreversible. Such a record could be a list of transactions such as with a cryptocurrency, but it also is possible for a blockchain to hold a variety of other information like legal contracts, state identifications, or a companys inventory.",

    text9: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,"
}

// var text = (text1)
// var counter = 1;
// const NewStack = () => {
//     if (counter < 2) { counter++;} 
//     else {counter--;}

//     var newSD = eval('text'+counter)
//     text = newSD;
// }

const generate = () => {
    // checking function is working or not.
    console.log("Hello from generate")

    // getting the paragraph div and select values
    const paraNo = document.getElementById('paraNo').value;
    const paraDiv = document.getElementById('data');

    // getting the select value 
    console.log(paraNo)

    // first clearing the previously filled paragraph div.
    paraDiv.innerHTML = "";

    // Looping to append random paragraph one by one

    for (var index = 0; index < paraNo; index++) {
        // Getting the paragraph from dictionary randomly.
        const randomIndex =  Math.floor(Math.random()*10);
        // console.log(text['text'+randomIndex]);

        // appending the random paragraph to div.
        const para = document.createElement("p");
        const br = document.createElement('br');
        para.innerText = text['text'+randomIndex];
        document.getElementById("data").appendChild(para);
        document.getElementById("data").appendChild(br);
    }
}